/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "cxaezpsbvnvdhfnnuldk"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4YWV6cHNidm52ZGhmbm51bGRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1OTc2OTMsImV4cCI6MjA3NjE3MzY5M30.4VQ6HF-3MXYCk-54o2syJKxUnTlJ-SaDmAy7uMFMcfg"